version: "0.0.1"

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
  
  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    networks:
      - mern-network
    
networks:
  mern-network:
    driver: bridge